services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./uc-server/data:/var/www/html/uc-server
      - ./bbs/data:/var/www/html/bbs
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - uc-server
      - bbs
  uc-server:
    build:
      context: ..
      dockerfile: ./apps-docker/uc-server/Dockerfile
    restart: unless-stopped
    container_name: uc-server
    volumes:
      - ./uc-server/data:/var/www/html/uc-server
    extra_hosts:
      - "bbs.17lifezone.cn:host-gateway"
    depends_on:
      - mysql
      - redis
  bbs:
    build:
      context: ..
      dockerfile: ./apps-docker/bbs/Dockerfile
    container_name: bbs
    restart: unless-stopped
    volumes:
      - ./bbs/data:/var/www/html/bbs
    extra_hosts:
      - "uc.17lifezone.cn:host-gateway"
    depends_on:
      - mysql
      - redis
  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    command: minio server /data --console-address ":9001" --ftp="address=:8021" --ftp="passive-port-range=30000-40000"
    ports:
      - "9000:9000"  # API 端口
      - "9001:9001"  # 控制台端口
      - "8021:8021"  # SFTP 端口
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=root_pass
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Shanghai
      - TZ=Asia/Shanghai
      - N8N_HOST=n8n.iehong.fun
      - N8N_PROTOCOL=https
    volumes:
      - n8n-data:/home/node/.n8n
  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    container_name: camunda
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=com.mysql.cj.jdbc.Driver
      - DB_URL=jdbc:mysql://mysql:3306/camunda_db?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      - DB_USERNAME=root
      - DB_PASSWORD=root_pass
      - WAIT_FOR=mysql:3306
      - TZ=Asia/Shanghai
      - JAVA_OPTS= -Duser.timezone=Asia/Shanghai
    depends_on:
      - mysql
  # Redis 缓存
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./redis/data:/data  # 数据持久化
  mysql:
    image: mysql:lts
    container_name: mysql
    command: 
      - --transaction-isolation=READ-COMMITTED
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
    volumes:
      - ./mysql/data:/var/lib/mysql  # 数据持久化
      - ./mysql/db-init:/docker-entrypoint-initdb.d  # 挂载初始化脚本

volumes:
  n8n-data: 
