<?php
/* *
* $Author ：PHPYUN开发团队
*
* 官网: http://www.phpyun.com
*
* 版权所有 2009-2021 宿迁鑫潮信息技术有限公司，并保留所有权利。
*
* 软件声明：未经授权前提下，不得用于商业运营、二次开发以及任何形式的再次发布。
*/
$arr_tpl = array ( 
	'emailupjob' => array (
		'name'=>'企业未更新职位',
		'type'=>'email',
		'config'=>'sy_email_upjob',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{username}'=>'企业名',    
		'{date}'=>'上次刷新时间',
	    '{day}'=>'未发布天数'
	),
	'emailaddjob' => array (
		'name'=>'企业未发布职位',
		'type'=>'email',
		'config'=>'sy_email_addjob',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{username}'=>'企业名',    
		'{date}'=>'上次发布时间',
	    '{day}'=>'未发布天数'    
	),
	'emailwebbirthday' => array (
		'name'=>'网站周年庆',
		'type'=>'email',
		'config'=>'sy_email_webbirthday',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{username}'=>'真实姓名',    
		'{year}'=>'年数',    
		'{date}'=>'创办日期' 
	),
	'emailuserwdl' => array (
		'name'=>'个人会员长期未登录',
		'type'=>'email',
		'config'=>'sy_email_userwdl',
		'cate'=>'user',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{username}'=>'用户名',  
		'{date}'=>'上次登录时间' 
	), 
	'emailcomwdl' => array (
		'name'=>'企业会员长期未登录',
		'type'=>'email',
		'config'=>'sy_email_comwdl',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{name}'=>'企业名称',  
		'{date}'=>'上次登录时间' 
	),
    'emailuserup' => array (
        'name'=>'个人会员未更新简历',
        'type'=>'email',
        'config'=>'sy_email_userup',
		'cate'=>'user',
        '{webname}'=>'网站名称',
        '{weburl}'=>'网站域名',
        '{webtel}'=>'网站电话',
        '{username}'=>'用户名',
        '{date}'=>'上次更新时间',
        '{day}'=>'未更新天数'
    ),
    'emailuseradd' => array (
        'name'=>'个人会员未发布简历',
        'type'=>'email',
        'config'=>'sy_email_useradd',
		'cate'=>'user',
        '{webname}'=>'网站名称',
        '{weburl}'=>'网站域名',
        '{webtel}'=>'网站电话',
        '{username}'=>'用户名',
        '{day}'=>'未发布简历天数',
        '{date}'=>'注册时间'
    ),
	'emailreg' => array (
		'name'=>'注册会员',
		'type'=>'email',
		'config'=>'sy_email_reg',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{username}'=>'用户名',
		'{password}'=>'密码',
		'{email}'=>'邮箱'
	),
	'emailyqms' => array (
		'name'=>'邀请面试',
		'type'=>'email',
		'config'=>'sy_email_yqms',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{company}'=>'公司名称',
		'{linkman}'=>'联系人',
		'{comtel}'=>'联系电话',
		'{username}'=>'求职者名称',
		'{jobname}'=>'职位名称',
		'{comemail}'=>'邮箱'
	),
	'emailyqmshf' => array (
		'name'=>'回复邀请面试',
		'type'=>'email',
		'config'=>'sy_email_yqmshf',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{cusername}'=>'回复人名称',
		'{typemsg}'=>'回复内容：拒绝、同意'
	),
	'emailgetpass' => array (
		'name'=>'找回密码',
		'type'=>'email',
		'config'=>'sy_email_getpass',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{username}'=>'用户名',
		'{code}'=>'验证码'
	),
	'emailfkcg' => array (
		'name'=>'付款成功',
		'type'=>'email',
		'config'=>'sy_email_fkcg',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{order_id}'=>'交易单号',
		'{price}'=>'金额',
		'{date}'=>'时间'
	),
	'emaillock' => array (
		'name'=>'会员锁定',
		'type'=>'email',
		'config'=>'sy_email_lock',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{username}'=>'用户名',
		'{lock_info}'=>'锁定原因',
	),
	'emailuserstatus' => array (
		'name'=>'会员审核',
		'type'=>'email',
		'config'=>'sy_email_userstatus',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{date}'=>'审核时间',
		'{auto_statis}'=>'审核说明'
	),
	'emailzzshtg' => array (
		'name'=>'职位审核成功',
		'type'=>'email',
		'config'=>'sy_email_zzshtg',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{date}'=>'通过时间',
		'{jobname}'=>'职位名称'
	),
	'emailzzshwtg' => array (
		'name'=>'职位审核未通过',
		'type'=>'email',
		'config'=>'sy_email_zzshwtg',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{date}'=>'通过时间',
		'{jobname}'=>'职位名称',
		'{status_info}'=>'审核原因'
	),
	'emailpartshtg' => array (
		'name'=>'兼职审核成功',
		'type'=>'email',
		'config'=>'sy_email_partshtg',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{date}'=>'通过时间',
		'{jobname}'=>'职位名称'
	),
	'emailpartshwtg' => array (
		'name'=>'兼职审核未通过',
		'type'=>'email',
		'config'=>'sy_email_partshwtg',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{date}'=>'通过时间',
		'{jobname}'=>'职位名称',
		'{status_info}'=>'审核原因'
	),
	'emailsqzw' => array (
		'name'=>'申请职位',
		'type'=>'email',
		'config'=>'sy_email_sqzw',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{jobname}'=>'职位名称',
		'{date}'=>'申请时间'
	),
	'emailsqzwhf' => array (
		'name'=>'申请职位回复',
		'type'=>'email',
		'config'=>'sy_email_sqzwhf',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{company}'=>'公司名称',
		'{jobname}'=>'职位名称'
	),
	'emailcert' => array (
		'name'=>'邮箱认证',
		'type'=>'email',
		'config'=>'sy_email_cert',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{url}'=>'链接地址',
		'{date}'=>'认证时间'
	),
	'emailcomcert' => array (
		'name'=>'企业资质审核',
		'type'=>'email',
		'config'=>'sy_email_comcert',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{comname}'=>'企业名称',
		'{certinfo}'=>'审核说明'
	),
	'emailusercert' => array (
		'name'=>'个人身份认证审核',
		'type'=>'email',
		'config'=>'sy_email_usercert',
		'cate'=>'user',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{username}'=>'用户名',
		'{certinfo}'=>'审核说明'
	),
	'emailjobed' => array (
		'name'=>'职位过期提醒',
		'type'=>'email',
		'config'=>'sy_email_jobed',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{com_name}'=>'公司名称',
		'{job_name}'=>'职位名称'
	),
	'emailremind' => array (
		'name'=>'会员提醒',
		'type'=>'email',
		'config'=>'sy_email_remind',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
	),
	'emailvipmr' => array (
		'name'=>'会员到期提醒',
		'type'=>'email',
		'config'=>'sy_email_vipmr',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{name}'=>'用户名称', 
		'{ratingname}'=>'服务名称', 
		'{date}'=>'过期时间',
	    '{day}'=>'即将过期天数'
	),
	'emailuserdy' => array (
		'name'=>'个人订阅',
		'type'=>'email',
		'config'=>'sy_email_userdy',
		'cate'=>'user',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{jobname}'=>'职位名称',
	),
	'emailcomdy' => array (
		'name'=>'邮件订阅',
		'type'=>'email',
		'config'=>'sy_email_comdy',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{resumename}'=>'简历名称',
	),
	'emailnotice' => array (
		'name'=>'自动发送职位通知',
		'type'=>'email',
		'config'=>'sy_email_notice',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{jobname}'=>'职位名称',
	),
	'emailclaim' => array (
		'name'=>'认领会员',
		'type'=>'email',
		'config'=>'sy_email_claim',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{url}'=>'认领地址',
	),
	'emailrecharge' => array (
		'name'=>'充值提醒',
		'type'=>'email',
		'config'=>'sy_email_recharge',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{username}'=>'用户名',
		'{name}'=>'姓名',
		'{price}'=>'金额',
		'{time}'=>'时间',
	),
	'emailpartapply' => array (
		'name'=>'兼职报名',
		'type'=>'email',
		'config'=>'sy_email_partapply',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{date}'=>'通过时间',
		'{username}'=>'用户名',
		'{jobname}'=>'职位名称',
	),
    'emailzphshtg' => array (
        'name'=>'招聘会审核通过',
        'type'=>'email',
        'config'=>'sy_email_zphshtg',
		'cate'=>'com',
        '{webname}'=>'网站名称',
        '{weburl}'=>'网站域名',
        '{webtel}'=>'网站电话',
        '{date}'=>'通过时间',
        '{zphname}'=>'招聘会名称',
    ),
    'emailzphshwtg' => array (
        'name'=>'招聘会审核未通过',
        'type'=>'email',
        'config'=>'sy_email_zphshwtg',
		'cate'=>'com',
        '{webname}'=>'网站名称',
        '{weburl}'=>'网站域名',
        '{webtel}'=>'网站电话',
        '{zphname}'=>'招聘会名称',
        '{status_info}'=>'审核原因'
    ),
    'emaillogouted' => array(
        'name'        =>  '注销账号成功通知',
        'type'        =>  'email',
        'config'=>'sy_email_logouted',
		'cate'=>'public',
        '{webname}'   =>  '网站名称',
        '{username}'  =>  '用户名'
    ),
	'msgdy' => array (
		'name'=>'订阅通知',
		'type'=>'msg',
		'config'=>'sy_msg_dy',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话'
	),
  	'msguserchange' => array (
		'name'=>'申请切换身份审核通知',
		'type'=>'msg',
		'config'=>'sy_msg_userchange',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
    	'{status}'=>'是否同意'
	),
	'msgvipmr' => array (
		'name'=>'会员到期提醒',
		'type'=>'msg',
		'config'=>'sy_msg_vipmr',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{name}'=>'用户名称', 
		'{ratingname}'=>'服务名称', 
		'{date}'=>'过期时间',
	    '{day}'=>'即将过期天数'
	),
	'msgcert' => array (
		'name'=>'手机认证',
		'type'=>'msg',
		'config'=>'sy_msg_cert',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{code}'=>'验证码',
		'{date}'=>'认证时间'
	),
	'msgreg' => array (
		'name'=>'注册会员',
		'type'=>'msg',
		'config'=>'sy_msg_reg',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{username}'=>'用户名',
		'{password}'=>'密码',
		'{email}'=>'邮箱'
	),
	'msglogin' => array (
		'name'=>'短信验证码登录',
		'type'=>'msg',
		'config'=>'sy_msg_login',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{code}'=>'验证码'
	),
    'msgcode' => array (
        'name'=>'通用短信验证码',
        'type'=>'msg',
        'config'=>'sy_msg_code',
		'cate'=>'public',
        '{webname}'=>'网站名称',
        '{weburl}'=>'网站域名',
        '{webtel}'=>'网站电话',
        '{code}'=>'验证码'
    ),
	'msgyqms' => array (
		'name'=>'邀请面试',
		'type'=>'msg',
		'config'=>'sy_msg_yqms',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{company}'=>'公司名称',
		'{jobname}'=>'邀请职位',
		'{linkman}'=>'联系人',
		'{comtel}'=>'联系电话',
		'{username}'=>'求职者名称',
		'{jobname}'=>'职位名称',
		'{comemail}'=>'邮箱',
	    
	    '{address}' => '面试地址',
	    '{date}' => '面试时间'
	),
	'msgyqmshf' => array (
		'name'=>'回复面试邀请',
		'type'=>'msg',
		'config'=>'sy_msg_yqmshf',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{cusername}'=>'回复人名称',
		'{typemsg}'=>'回复内容：拒绝、同意'
	),
	'msgfkcg' => array (
		'name'=>'付款成功',
		'type'=>'msg',
		'config'=>'sy_msg_fkcg',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{order_id}'=>'交易单号',
		'{price}'=>'金额',
		'{date}'=>'时间'
	),
	'msgzzshtg' => array (
		'name'=>'职位审核通过',
		'type'=>'msg',
		'config'=>'sy_msg_zzshtg',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{date}'=>'通过时间',
		'{jobname}'=>'职位名称'
	),
	'msgzzshwtg' => array (
		'name'=>'职位审核未通过',
		'type'=>'msg',
		'config'=>'sy_msg_zzshwtg',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{date}'=>'通过时间',
		'{jobname}'=>'职位名称',
		'{status_info}'=>'审核原因',
	),
	'msgpartshtg' => array (
		'name'=>'兼职审核通过',
		'type'=>'msg',
		'config'=>'sy_msg_partshtg',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{date}'=>'通过时间',
		'{jobname}'=>'职位名称'
	),
	'msgpartshwtg' => array (
		'name'=>'兼职审核未通过',
		'type'=>'msg',
		'config'=>'sy_msg_partshwtg',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{date}'=>'通过时间',
		'{jobname}'=>'职位名称',
		'{status_info}'=>'审核原因',
	),
	'msggetpass' => array (
		'name'=>'找回密码',
		'type'=>'msg',
		'config'=>'sy_msg_getpass',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{username}'=>'用户名',
		'{code}'=>'验证码'),
	'msgsqzw' => array (
		'name'=>'申请职位',
		'type'=>'msg',
		'config'=>'sy_msg_sqzw',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{jobname}'=>'职位名称',
		'{date}'=>'申请时间',
	    
	),
	'msgsqzwhf' => array (
		'name'=>'申请职位回复',
		'type'=>'msg',
		'config'=>'sy_msg_sqzwhf',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{company}'=>'公司名称',
		'{jobname}'=>'职位名称'
		),
	'msgremind' => array (
		'name'=>'会员提醒',
		'type'=>'msg',
		'config'=>'sy_msg_remind',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话'
	),
	'msgclaim' => array (
		'name'=>'认领会员',
		'type'=>'msg',
		'config'=>'sy_msg_claim',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{url}'=>'认领地址',
	),
	'msgcomdy' => array (
		'name'=>'企业订阅',
		'type'=>'msg',
		'config'=>'sy_msg_comdy',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{resumename}'=>'简历名称'
	),
	'msguserdy' => array (
		'name'=>'个人订阅',
		'type'=>'msg',
		'config'=>'sy_msg_userdy',
		'cate'=>'user',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{jobname}'=>'职位名称'
	),
	'msgnotice' => array (
		'name'=>'自动发送职位通知',
		'type'=>'msg',
		'config'=>'sy_msg_notice',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{jobname}'=>'职位名称',
	),
	'msgregcode' => array (
		'name'=>'注册验证码',
		'type'=>'msg',
		'config'=>'sy_msg_regcode',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{code}'=>'验证码',
	),
	'msgrecharge' => array (
		'name'=>'充值提醒',
		'type'=>'msg',
		'config'=>'sy_msg_recharge',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{username}'=>'用户名',
		'{name}'=>'姓名',
		'{price}'=>'金额',
		'{time}'=>'时间',
	),
	'msgpartapply' => array (
		'name'=>'兼职报名',
		'type'=>'msg',
		'config'=>'sy_msg_partapply',
		'cate'=>'com',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{username}'=>'用户名',
		'{jobname}'=>'职位名称',
	),
    'msgresumestate' => array (
        'name'=>'简历审核',
        'type'=>'msg',
        'config'=>'sy_msg_resumestate',
		'cate'=>'user',
        '{webname}'=>'网站名称',
        '{weburl}'=>'网站域名',
        '{webtel}'=>'网站电话',
        '{resumename}'=>'简历名称',
        '{state_n}'=>'简历状态'
    ),
    'msgwebbirthday' => array (
        'name'=>'网站周年庆',
        'type'=>'msg',
        'config'=>'sy_msg_webbirthday',
		'cate'=>'public',
        '{webname}'=>'网站名称',
        '{weburl}'=>'网站域名',
        '{webtel}'=>'网站电话',
        '{username}'=>'真实姓名',
        '{year}'=>'年数',
        '{date}'=>'创办日期'
    ),
    'msguseradd' => array (
        'name'=>'个人会员未发布简历',
        'type'=>'msg',
        'config'=>'sy_msg_useradd',
		'cate'=>'user',
        '{webname}'=>'网站名称',
        '{weburl}'=>'网站域名',
        '{webtel}'=>'网站电话',
        '{username}'=>'用户名',
        '{day}'=>'未发布简历天数',
        '{date}'=>'注册时间'
    ),
    'msguserup' => array (
        'name'=>'个人会员未更新简历',
        'type'=>'msg',
        'config'=>'sy_msg_userup',
		'cate'=>'user',
        '{webname}'=>'网站名称',
        '{weburl}'=>'网站域名',
        '{webtel}'=>'网站电话',
        '{username}'=>'用户名',
        '{date}'=>'上次更新时间',
        '{day}'=>'未更新天数'
    ),
    'msgaddjob' => array (
        'name'=>'企业未发布职位提醒',
        'type'=>'msg',
        'config'=>'sy_msg_addjob',
		'cate'=>'com',
        '{webname}'=>'网站名称',
        '{weburl}'=>'网站域名',
        '{webtel}'=>'网站电话',
        '{username}'=>'企业名',
        '{date}'=>'上次发布时间',
        '{day}'=>'未发布天数'
    ),
    'msgupjob' => array (
        'name'=>'企业职位未刷新提醒',
        'type'=>'msg',
        'config'=>'sy_msg_upjob',
		'cate'=>'com',
        '{webname}'=>'网站名称',
        '{weburl}'=>'网站域名',
        '{webtel}'=>'网站电话',
        '{username}'=>'企业名',
        '{date}'=>'上次刷新时间',
        '{day}'=>'未发布天数'
    ),
	'msguserstatus' => array (
		'name'=>'会员审核',
		'type'=>'msg',
		'config'=>'sy_msg_userstatus',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{date}'=>'审核时间',
		'{auto_statis}'=>'审核说明'
	),
	'msglock' => array (
		'name'=>'会员锁定',
		'type'=>'msg',
		'config'=>'sy_msg_lock',
		'cate'=>'public',
		'{webname}'=>'网站名称',
		'{weburl}'=>'网站域名',
		'{webtel}'=>'网站电话',
		'{username}'=>'用户名',
		'{lock_info}'=>'锁定原因',
	),
    'msglogouted' => array(
        'name'        =>  '注销账号成功通知',
        'type'        =>  'msg',
        'config'	  =>  'sy_msg_logouted',
		'cate'		  =>  'public',
        '{webname}'   =>  '网站名称',
        '{username}'  =>  '用户名'
    ),
);
